// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbheelDRKrMidYKE_0kC_9tS-TpLFSCaY',
    appId: '1:99443109366:web:364c83a8f5663b56196bd7',
    messagingSenderId: '99443109366',
    projectId: 'project-cookita-apps',
    authDomain: 'project-cookita-apps.firebaseapp.com',
    storageBucket: 'project-cookita-apps.firebasestorage.app',
    measurementId: 'G-G94JYF9F4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkvm8pkHuDNqo8c_Jpe0R0SAECCE0jnew',
    appId: '1:99443109366:android:bbc23c1a2e27b498196bd7',
    messagingSenderId: '99443109366',
    projectId: 'project-cookita-apps',
    storageBucket: 'project-cookita-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF0EjLhVerSgvR-pW_mWsHgI2L2i_bs4E',
    appId: '1:99443109366:ios:7855dbb313d9d7ce196bd7',
    messagingSenderId: '99443109366',
    projectId: 'project-cookita-apps',
    storageBucket: 'project-cookita-apps.firebasestorage.app',
    iosBundleId: 'com.example.cookitaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF0EjLhVerSgvR-pW_mWsHgI2L2i_bs4E',
    appId: '1:99443109366:ios:7855dbb313d9d7ce196bd7',
    messagingSenderId: '99443109366',
    projectId: 'project-cookita-apps',
    storageBucket: 'project-cookita-apps.firebasestorage.app',
    iosBundleId: 'com.example.cookitaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbheelDRKrMidYKE_0kC_9tS-TpLFSCaY',
    appId: '1:99443109366:web:a936900585a898fa196bd7',
    messagingSenderId: '99443109366',
    projectId: 'project-cookita-apps',
    authDomain: 'project-cookita-apps.firebaseapp.com',
    storageBucket: 'project-cookita-apps.firebasestorage.app',
    measurementId: 'G-TG9JSHQNE1',
  );

}